---
is_debug: true
listen:
  bind_ip: "localhost"
  port: "8080"
db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "qwerty"
  dbname: "reports_system"
  ssl_mode: "disable"
  migrations_path: "etc/migrations"
jwt:
  secret: "$ecr3t"
