basePath: /
definitions:
  account.GetAccountDTO:
    properties:
      email:
        type: string
      name:
        type: string
      username:
        type: string
    type: object
  account.LoginAccountDTO:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  account.RegisterAccountDTO:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  account.WithTokenDTO:
    properties:
      email:
        type: string
      name:
        type: string
      token:
        type: string
      username:
        type: string
    type: object
  e.ErrorResponse:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  label.CreateLabelDTO:
    properties:
      department:
        type: string
      name:
        type: string
    required:
    - department
    - name
    type: object
  label.GetAllLabelsDTO:
    properties:
      labels:
        items:
          $ref: '#/definitions/label.Label'
        type: array
    type: object
  label.Label:
    properties:
      department:
        type: string
      id:
        type: integer
      name:
        type: string
    required:
    - department
    - name
    type: object
  label.UpdateLabelDTO:
    properties:
      department:
        type: string
      name:
        type: string
    type: object
  report.CreateReportDTO:
    properties:
      body:
        type: string
      department:
        type: string
      header:
        type: string
    required:
    - department
    - header
    type: object
  report.GetAllReportsDTO:
    properties:
      reports:
        items:
          $ref: '#/definitions/report.Report'
        type: array
    type: object
  report.Report:
    properties:
      body:
        type: string
      department:
        type: string
      edited:
        type: string
      header:
        type: string
      id:
        type: integer
      labels:
        description: '[]label.Label'
        items:
          $ref: '#/definitions/label.Label'
        type: array
      shortBody:
        type: string
    type: object
  report.UpdateReportDTO:
    properties:
      body:
        type: string
      department:
        type: string
      header:
        type: string
      id:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for reports-taking applications
  termsOfService: http://swagger.io/terms/
  title: RS
  version: "1.0"
paths:
  /api/v1/accounts/:id:
    get:
      consumes:
      - application/json
      description: get account
      operationId: get-account
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.GetAccountDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      summary: getAccount
      tags:
      - account
  /api/v1/accounts/login:
    post:
      consumes:
      - application/json
      description: login
      operationId: login
      parameters:
      - description: credentials
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/account.LoginAccountDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.WithTokenDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      summary: Login
      tags:
      - account
  /api/v1/accounts/register:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: account info
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/account.RegisterAccountDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      summary: Register
      tags:
      - account
  /api/v1/labels:
    get:
      consumes:
      - application/json
      description: get labels from user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/label.GetAllLabelsDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all labels
      tags:
      - labels
  /api/v1/labels/{id}:
    delete:
      consumes:
      - application/json
      description: delete one label by ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete one label by ID
      tags:
      - labels
    get:
      consumes:
      - application/json
      description: get one label by ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/label.Label'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get one label by ID
      tags:
      - labels
    patch:
      consumes:
      - application/json
      description: update one label by ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: label info
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/label.UpdateLabelDTO'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update label by ID
      tags:
      - labels
  /api/v1/reports:
    get:
      consumes:
      - application/json
      description: create report
      parameters:
      - description: reports search by label
        in: query
        name: label
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/report.GetAllReportsDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all reports from user filter by label
      tags:
      - reports
    post:
      consumes:
      - application/json
      description: create report
      parameters:
      - description: report content
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/report.CreateReportDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create report
      tags:
      - reports
  /api/v1/reports/{id}:
    delete:
      consumes:
      - application/json
      description: delete report
      operationId: delete-report
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Delete Report
      tags:
      - reports
    get:
      consumes:
      - application/json
      description: get report by id
      operationId: get-report-by-id
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/report.Report'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get Report By Id
      tags:
      - reports
    patch:
      consumes:
      - application/json
      description: update report
      operationId: update-report
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: report content
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/report.UpdateReportDTO'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Update Report
      tags:
      - reports
  /api/v1/reports/{id}/labels:
    get:
      consumes:
      - application/json
      description: get labels for report
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/label.GetAllLabelsDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get all labels on one report
      tags:
      - labels
    post:
      consumes:
      - application/json
      description: create label
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: label info
        in: body
        name: dto
        required: true
        schema:
          $ref: '#/definitions/label.CreateLabelDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create label
      tags:
      - labels
  /api/v1/reports/{id}/labels/{label_id}:
    delete:
      consumes:
      - application/json
      description: detach label by ID from report by ID
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: label id
        in: path
        name: label_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/e.ErrorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/e.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Detach label by ID from report by ID
      tags:
      - reports
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
